services:
  host:
    build:
      context: .
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: >
        mongosh --quiet --eval
        "try { rs.status().ok } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}).ok }"
      interval: 5s
      timeout: 5s
      retries: 10
